import '~/styles/globals.css'
import { ThemeProvider } from '~/components/theme-provider'
import { type Metadata } from 'next'
import { Geist } from 'next/font/google'
import { useQueryClient, QueryClientProvider } from '@tanstack/react-query'
import { QueryProvider } from '~/components/query-provider'
import { Toaster } from 'sonner'

export const metadata: Metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
}

const geist = Geist({
  subsets: ['latin'],
  variable: '--font-geist-sans',
})

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body>
        <QueryProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <Toaster />
            {children}
          </ThemeProvider>
        </QueryProvider>
      </body>
    </html>
  )
}
